/* villa-lang.js — 6-мовний перемикач + ПОВНИЙ переклад вілл-сторінок */
var UI={
en:{back:"← Back to All Villas",specs:"Villa specifications",perfect:"Perfect for",rules:"House rules",rules_note2:"cleaning fee and electricity charges apply. See",rules_link:"full villa policies",location:"Location",loc_note:"North Pattaya, Soi 12 — 5 minutes from Terminal 21, Pattaya Beach, Alcazar Cabaret and Art in Paradise. Quiet gated community with 24/7 security.",langs:"Languages spoken:",langs_val:"English, Russian, Thai, Ukrainian.",cta_sub:"Send us your dates — we'll confirm availability in minutes.",book:"Book via WhatsApp",seeall:"See All 5 Villas",size:"Size",brba:"Bedrooms / bathrooms",beds:"Beds",guests:"Max guests",pool:"Pool",ent:"Entertainment",wifipark:"WiFi / parking",petsdep:"Pets / deposit",price:"From price"},
ua:{back:"← До всіх вілл",specs:"Характеристики вілли",perfect:"Ідеально для",rules:"Правила проживання",rules_note2:"стягується плата за прибирання та електроенергію. Див.",rules_link:"повні правила вілли",location:"Локація",loc_note:"Північна Паттайя, Soi 12 — 5 хвилин до Terminal 21, пляжу, Alcazar та Art in Paradise. Тиха закрита спільнота з охороною 24/7.",langs:"Мови:",langs_val:"Англійська, російська, тайська, українська.",cta_sub:"Надішліть дати — підтвердимо за лічені хвилини.",book:"Бронювати у WhatsApp",seeall:"Усі 5 вілл",size:"Площа",brba:"Спальні / ванні",beds:"Ліжка",guests:"Макс. гостей",pool:"Басейн",ent:"Розваги",wifipark:"WiFi / парковка",petsdep:"Тварини / депозит",price:"Ціна від"},
ru:{back:"← Ко всем виллам",specs:"Характеристики виллы",perfect:"Идеально для",rules:"Правила проживания",rules_note2:"взимается плата за уборку и электричество. См.",rules_link:"полные правила виллы",location:"Локация",loc_note:"Северная Паттайя, Soi 12 — 5 минут до Terminal 21, пляжа, Alcazar и Art in Paradise. Тихое закрытое сообщество с охраной 24/7.",langs:"Языки:",langs_val:"Английский, русский, тайский, украинский.",cta_sub:"Пришлите даты — подтвердим за минуты.",book:"Бронировать в WhatsApp",seeall:"Все 5 вилл",size:"Площадь",brba:"Спальни / ванные",beds:"Кровати",guests:"Макс. гостей",pool:"Бассейн",ent:"Развлечения",wifipark:"WiFi / парковка",petsdep:"Питомцы / депозит",price:"Цена от"},
th:{back:"← กลับวิลล่าทั้งหมด",specs:"สเปควิลล่า",perfect:"เหมาะสำหรับ",rules:"กฎการพัก",rules_note2:"มีค่าทำความสะอาดและค่าไฟ ดู",rules_link:"กฎเต็มของวิลล่า",location:"ที่ตั้ง",loc_note:"พัทยาเหนือ Soi 12 — 5 นาทีถึง Terminal 21 หาดพัทยา Alcazar และ Art in Paradise หมู่บ้านมีรั้ว รปภ. 24 ชม.",langs:"ภาษา:",langs_val:"อังกฤษ รัสเซีย ไทย ยูเครน",cta_sub:"ส่งวันที่มา — ยืนยันในนาที",book:"จองผ่าน WhatsApp",seeall:"ดูวิลล่าทั้ง 5",size:"พื้นที่",brba:"ห้องนอน / ห้องน้ำ",beds:"เตียง",guests:"สูงสุด",pool:"สระว่ายน้ำ",ent:"ความบันเทิง",wifipark:"WiFi / ที่จอด",petsdep:"สัตว์เลี้ยง / มัดจำ",price:"ราคาเริ่ม"},
zh:{back:"← 返回所有别墅",specs:"别墅规格",perfect:"适合",rules:"入住规则",rules_note2:"需收取清洁费和电费。见",rules_link:"别墅完整规则",location:"位置",loc_note:"北芭提雅Soi 12——距Terminal 21、海滩、Alcazar和Art in Paradise 5分钟。24/7安保封闭社区。",langs:"语言:",langs_val:"英、俄、泰、乌。",cta_sub:"发送日期——几分钟内确认。",book:"WhatsApp预订",seeall:"查看全部5栋",size:"面积",brba:"卧/卫",beds:"床",guests:"最多入住",pool:"泳池",ent:"娱乐",wifipark:"WiFi/停车",petsdep:"宠物/押金",price:"价格从"},
ko:{back:"← 모든 빌라로",specs:"빌라 사양",perfect:"추천 대상",rules:"숙박 규칙",rules_note2:"청소비 및 전기 요금이 부과됩니다. 보기",rules_link:"빌라 전체 규칙",location:"위치",loc_note:"북파타야 Soi 12 — Terminal 21, 해변, Alcazar, Art in Paradise까지 5분. 24/7 보안 게이트 커뮤니티.",langs:"언어:",langs_val:"영, 러, 태, 우크라이나어.",cta_sub:"날짜를 보내주세요 — 몇 분 내 확인.",book:"WhatsApp 예약",seeall:"빌라 5동 보기",size:"면적",brba:"침실/욕실",beds:"침대",guests:"최대 인원",pool:"풀",ent:"오락",wifipark:"WiFi/주차",petsdep:"애완/보증금",price:"가격"}};
var lang="en";
function t(k){if(window.VILLA_T&&VILLA_T[lang]&&VILLA_T[lang][k]!=null)return VILLA_T[lang][k];return (UI[lang]&&UI[lang][k]!=null)?UI[lang][k]:null}
function villaLang(){
 lang=localStorage.getItem("mv_lang")||"en";if(!UI[lang])lang="en";
 document.documentElement.lang=(lang==="ua"?"uk":lang==="zh"?"zh-CN":lang);
 document.querySelectorAll("[data-i18n]").forEach(function(el){var v=t(el.dataset.i18n);if(v!=null)el.innerHTML=v});
 if(window.VILLA_DESC){var d=document.getElementById("vDesc");if(d)d.innerHTML=VILLA_DESC[lang]||VILLA_DESC.en}
 var sw=document.getElementById("vLangs");
 if(sw){sw.innerHTML="";["en","ua","ru","th","zh","ko"].forEach(function(l){var b=document.createElement("button");b.textContent={en:"EN",ua:"UA",ru:"RU",th:"TH",zh:"中文",ko:"한국어"}[l];b.style.cssText="border:0;background:"+(l===lang?"#d9b36a":"transparent")+";color:"+(l===lang?"#231a08":"#9fb0a5")+";font-weight:700;font-size:12px;padding:5px 8px;border-radius:9px;cursor:pointer";b.onclick=function(){localStorage.setItem("mv_lang",l);villaLang()};sw.appendChild(b)})}
}
document.addEventListener("DOMContentLoaded",villaLang);